kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lightrun-volumeclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi